### ISSUE TITLE
Question: any interest in switching to `debug` for debugging?

### ISSUE THREAD

**Issue by nemtsov** [OptimalBits/node_acl#147]
Do you have any interest in switching to [debug](https://github.com/visionmedia/debug) for debugging?
I can submit a PR if there's any appetite for it.

It can be done in a way that a custom logger may be provided as well (in case the existing one is used to log to a remote system or the fs), via overriding the `debug.log` method (as shown in the [stderr vs stdout](https://github.com/visionmedia/debug#stderr-vs-stdout) example.

**Comment by manast** [comment]
I am not so keen on debug. These days I often use [bunyan](https://github.com/trentm/node-bunyan)

**Comment by nemtsov** [comment]
Me too. I assume you:

```js
var log = bunyan.createLogger({name: 'acl'});
var acl = new Acl(backend, log);
```

and then tweak the levels in bunyan. 
Ok closing.
