### ISSUE TITLE
Wildcard for resources

### ISSUE THREAD

**Issue by lucaskenda** [OptimalBits/node_acl#151]
I'm using memory backend and when i put * in permissions like this:
acl.allow('admin', ['blogs','forums'], '*');
it works ok, but if I use wildcard for resources:
acl.allow('admin', '*', '*')
it doesn't allow me.
Its just a bug or you can't use * for resources?
Thanks!

**Comment by trainerbill** [comment]
I was wondering the same thing.  Or be able to do

/comments/*

which would allow 

/comments/:id/action/:somethingelse

etc.

Otherwise my ACL file is getting huge!

**Comment by futurechan** [comment]
Have you tried the regexp backend?

**Comment by lucaskenda** [comment]
@futurechan How can i use regexp at backend?

**Comment by futurechan** [comment]
@lucaskenda https://github.com/futurechan/node_acl-mem-regexp There as some examples. Let me know if you have any questions by opening an issue against that repo.

**Comment by lucaskenda** [comment]
Thanks! This is what i was looking for.
