### ISSUE TITLE
Unexpected result from `isAllowed`

### ISSUE THREAD

**Issue by ErikEvenson** [OptimalBits/node_acl#153]
This code:

```javascript
  var acl = require('acl');
  acl = new acl(new acl.memoryBackend());

  acl.allow('eevenson', 'test', 'view', function(err) {
    acl.isAllowed('eevenson', 'test', 'view', function(err, allow) {
      console.log('xxx', err, allow);
    });
  });
```

logs `xxx null false`.  I would have expected it to log `xxx null true`.

**Comment by jonmassot** [comment]
see `isAllowed` definition : https://github.com/OptimalBits/node_acl#isallowed-userid-resource-permissions-functionerr-allowed-

`acl.isAllowed` expect to have the userID where `allow` gives access to roles, not users. Or maybe I don't really understand your code.

**Comment by ErikEvenson** [comment]
@jonmassot perfect -- thanks.  I missed the role/user layer of indirection.  Closing.
