### ISSUE TITLE
How to access acl in controllers or other custom middleware

### ISSUE THREAD

**Issue by jbeckton** [OptimalBits/node_acl#163]
I have acl up and running, configured the instance in my app.js file. I have all my auth logic in an auth controller which contains methods called when a route is hit. But I am not clear on how to access the acl instance i configured in the app.js file.

**Comment by jonmassot** [comment]
what backstore/database are you using with ACL?

**Comment by jbeckton** [comment]
mongoose

**Comment by nharris85** [comment]
@jbeckton you want to look into module.exports in node. Export your instantiated acl object and require() it in each node js file you need.

**Comment by jbeckton** [comment]
Ok, I have module.exports = acl in my app.js then var acl = require('acl'); in my auth controller. in debug I can se that acl instance has some properties but when I call acl.userRoles() I get an error saying acl.userRoles is not a function.

**Comment by jbeckton** [comment]
I finally figured it out, thanks for the assistance!

**Comment by Markkos89** [comment]
@jbeckton  and how did you did it? :)

**Comment by vijaykotha** [comment]
Hi I am not able to find a way that acl itself finds the  role of the user from response user json.
This is my configuration

var acl = require('acl');
acl = new acl(new acl.memoryBackend());
acl.addUserRoles('12345', 'Analyst'); // Right now I am setting the role of the user id 12345 as Analyst explicitly. So I need to implement this in a way to find the user's role dynamically.
acl.allow([
           {
               roles:['Analyst', 'Supervisor'],
               allows:[
                   {resources:'/reports', permissions:'*'},
               ]
           }
       ]);

clientRouter.get('/reports', passportutil.isAuthenticated, acl.middleware(), function(req, res) {
	res.sendFile(path.join(__dirname, 'html/reports.html'));
});

Please help me out.
