### ISSUE TITLE
is this project about to die?

### ISSUE THREAD

**Issue by k1ng440** [OptimalBits/node_acl#188]
Hello,
I see a lot of pull requests that fixes a lot of bugs but still pending for long time. 

looking forward to your response @manast 

Thanks

**Comment by k1ng440** [comment]
also mongoBackend is broken. https://github.com/OptimalBits/node_acl/issues/141

**Comment by akaustel** [comment]
I sure hope not. This is the best generic ACL implementation I've found so far for our needs. I can't speak for OptimalBits though.

**Comment by manast** [comment]
@k1ng440  which fixes are you referring too?
Regarding mongo, it was a mistake to have it in the main repo, it was developed by a contributor, and I cannot really support it...

**Comment by k1ng440** [comment]
there is some warning about deprecated bluebird function defer(). can you fix it please?
