### ISSUE TITLE
acl.middleware Error heading

### ISSUE THREAD

**Issue by chickencyj** [OptimalBits/node_acl#207]
using acl.middleware, If the user do not have the permissions,it will return  
HttpError: Insufficient permissions to access resource and send res.status 500 to Client,
and how can I catch the error then  I can change the Error's description and headler it by myself

**Comment by chickencyj** [comment]
i found the way ro resolve it  😁

**Comment by roysclickers** [comment]
Share with us, tnx

**Comment by shanutthankachan** [comment]
Share with us, tnx
