### ISSUE TITLE
Collection name contains a path separator '/' and can't be dumped to the filesystem

### ISSUE THREAD

**Issue by itsay** [OptimalBits/node_acl#229]
acl create collection name with '/' (ex: acl_allows_/user), so when I use  mongodump to create backup, mongodump throw exception: Failed: "db.acl_allows_/user" contains a path separator '/' and can't be dumped to the filesystem

Does anyone know how to fix it?
Thanks

**Comment by Trenrod** [comment]
There are already 2 PR for this issue. Also waiting for their release ^^

https://github.com/OptimalBits/node_acl/pull/228
https://github.com/OptimalBits/node_acl/pull/113

**Comment by john-osullivan** [comment]
Any movement on reviewing #228 and #113 ?  I'm implementing node-acl in my app right now and the planned naming convention depended on '/'!

**Comment by manast** [comment]
done, released in version 0.4.11.
