### ISSUE TITLE
Does it only work async ?

### ISSUE THREAD

**Issue by asotog** [OptimalBits/node_acl#245]
Is there any way to make it work sync, using a single backend ? so i can say like:

`const isAllowed = acl.isAllowed('johndoe', 'blogs', 'write');`

so based on that wanted to not show for example a create new blog button.

wanted to use the package in the client side, to render or not ui sections based on roles

**Comment by manast** [comment]
You can do that using async code as well :) . I will close this issue as unrelated for acl.
