### ISSUE TITLE
MongoDB backend: Use a single collection to hold allows_RESOURCE

### ISSUE THREAD

**Issue by inolasco** [OptimalBits/node_acl#48]
Using a mongodb backend, Is it really necessary to create one collection for every resource? My DB got bloated with a lot of collections after setting up just a few of my routes paths as resource names. And each of these collections only contain one document like this:

allows_/public/states
    {
      "_id": { "$oid" : "53488267b1d5dc96edf1c378" },
      "key": "guest",
      "get": true
    }

Wouldn't it be better to have a single collection allows_resource with documents like this:
    {
      "_id": { "$oid" : "53488267b1d5dc96edf1c378" },
      "name": "/public/states",
      "key": "guest",
      "get": true
    }

If it were this way, I could define my resources by full paths, including any id's in them (like /books/123/pages/456) and not needing to normalize them (to /books/:id/pages/:id), and using the bundled middleware would be easier. But as it is now, the DB would get REALLY bloated :(

The rest is great though

**Comment by SnehaLanjewar** [comment]
hi, @manast @inolasco can you please show a sample example using a single collection for allow_resource.

**Comment by inolasco** [comment]
@SnehaLanjewar Sure, this is the code I use in my prod app:

```
var ACL = require('acl');

// Using existing mongoose connection
var db = mongoose.connection.db;

// Create ACL mongo backend, using a single collection.
var mongoBackend = new ACL.mongodbBackend(db, 'acl_', true);

// Create ACL
var acl = new ACL(mongoBackend);
```

The single-collection is just the third parameter when creating the mongo backend.
