### ISSUE TITLE
Permissions not set after using resources with * symbol

### ISSUE THREAD

**Issue by ilya-khaustov** [OptimalBits/node_acl#94]
Here is brief report:

		$ head node_modules/acl/package.json 
		{
		  "name": "acl",
		  "version": "0.4.7",
		  "description": "An Access Control List module, based on Redis with Express middleware support",
		  "keywords": [
		    "middleware",
		    "acl",
		    "web"
		  ],
		  "repository": {

		$ node

		> acl = require('acl')

		> acl = new acl(new acl.memoryBackend())

		> acl.allow('john','client.*','get')

		> acl.whatResources('john', function(err, r) { console.log(err); console.log(r); });

		null
		{ 'client.*': [ 'get' ] }

		> acl.allow('peter','client.name','get')

		> acl.whatResources('peter', function(err, r) { console.log(err); console.log(r); });
		
		null
		{ 'client.name': [] }

**Comment by manast** [comment]
Thats not supported on acl, you may check this one instead: https://github.com/futurechan/node_acl-mem-regexp

**Comment by ilya-khaustov** [comment]
I don't need regexp, all I need for ACL is to keep strings with different symbols and work as expected. For now I use ? symbol that means access to all fields of model. Example: admin has access to client.? resource, which means he can edit or view every field of Client model. Again, I handle this logic myself, and it would be much more convinient to use * symbol there.

If it is not a bug, then can you show an example of using this "feature"?
